pull_request_rules:
  - name: label scala-steward's PRs
    conditions:
      - or:
          - author=scala-steward-rstraub
    actions:
      label:
        add:
          - dependency-update
        remove: [ ]
  - name: merge scala-steward's PRs
    conditions:
      - or:
          - author=scala-steward-rstraub
      - status-success=Quality Check
    actions:
      merge:
        method: merge
